//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserConnect
{
    public partial class Register
    {
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;
        protected global::System.Web.UI.WebControls.TextBox txtLastName;
        protected global::System.Web.UI.WebControls.RadioButtonList rblGender;
        protected global::System.Web.UI.WebControls.TextBox txtBirthdate;
        protected global::System.Web.UI.WebControls.FileUpload fuPhoto;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        protected global::System.Web.UI.WebControls.TextBox txtPhone;
        protected global::System.Web.UI.WebControls.TextBox txtAddress;
        protected global::System.Web.UI.WebControls.TextBox txtPincode;
        protected global::System.Web.UI.WebControls.TextBox txtCity;
        protected global::System.Web.UI.WebControls.DropDownList ddlState;
        protected global::System.Web.UI.WebControls.TextBox lblMessage;
        protected global::System.Web.UI.WebControls.Button btnRegister;
    }
}

